version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
