version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  apt_packages:
    - graphviz

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
